export const CLIMATE_CAUSES = {
  temperature: [
    { title: 'Higher land is usually cooler', why: 'Air pressure decreases with height because there is less air above you. When air rises into lower pressure, it expands and cools. In the lowest layer of the atmosphere, temperature usually decreases with elevation.', connection: 'High Blue Ridge and Appalachian mountain locations are usually cooler than low-lying Tidewater. On some clear, calm nights, cold, dense air settles in valleys, making a valley colder than a slope above it.', source: 'https://www.weather.gov/bgm/WeatherInActionDownSlopeWinds', sourceLabel: 'NWS: rising and sinking air' },
    { title: 'Water slows temperature changes', why: 'Water takes more energy than the same mass of land material to warm by one degree, and mixing spreads heat through the water. The ocean warms and cools more slowly than land. Winds can carry that ocean influence inland.', connection: 'Near the Atlantic and Chesapeake Bay, water can soften winter cold and cool a hot summer afternoon with a sea breeze. The coast is not hotter every day; its low elevation and southeastern location also help explain its warmer annual average.', source: 'https://www.ndbc.noaa.gov/education/seabreeze_ans.shtml', sourceLabel: 'NOAA: land, water, and sea breezes' },
    { title: 'Sunshine and moving air matter, too', why: 'Farther north, sunlight generally reaches the ground at a lower angle, spreading its energy over a larger area. Virginia’s north–south difference is modest; elevation and the movement of warm and cold air also matter.', connection: 'Northern Virginia often has colder winters than southeastern Virginia. But a cold front can cool much of the state, and a high southern mountain can be colder than a low northern town.', source: 'https://statesummaries.ncics.org/chapter/va/', sourceLabel: 'NOAA: Virginia climate patterns' },
  ],
  snowfall: [
    { title: 'Mountains can help make clouds', why: 'Wind can push moist air up a mountain. As the air expands and cools, water vapor can condense into tiny cloud droplets; ice crystals can grow in cold clouds. With enough moisture and growth, rain or snow may fall.', connection: 'Slopes facing a moist wind can get extra precipitation. If that air is cold enough, it can add mountain snow. Meteorologists call this mountain lifting “orographic lift.”', source: 'https://www.weather.gov/jkl/education', sourceLabel: 'NWS: how clouds and precipitation form' },
    { title: 'A valley can sit in a rain shadow', why: 'After air passes over a ridge, it may sink, compress, and warm. This reduces relative humidity and can help clouds evaporate. Some moisture may already have fallen on the first slope, leaving less precipitation on the sheltered side.', connection: 'Parts of the Shenandoah Valley are relatively dry because surrounding mountains can shelter them. Which slope is wetter depends on wind direction. “Cooler” does not automatically mean “wetter” or “snowier.”', source: 'https://www.dcr.virginia.gov/natural-heritage/natural-communities/document/ncoverviewphys-veg.pdf', sourceLabel: 'Virginia DCR: mountains and rain shadows' },
    { title: 'Snow needs moisture and a cold path down', why: 'Snowflakes can form in cold clouds, but a warm layer below can melt them into rain. Partly melted or refrozen precipitation can become sleet; liquid drops can freeze on cold surfaces as freezing rain. The whole path from cloud to ground matters.', connection: 'High mountain locations more often keep a cold enough path for snow. Milder coastal air more often allows melting. A coastal storm can supply lots of moisture, though, so a cold enough storm can bring snow even to Tidewater. A storm’s route changes where cold air and moisture meet.', source: 'https://www.weather.gov/arx/why_wintrymix', sourceLabel: 'NWS: why winter precipitation changes type' },
  ],
} as const;

export const MOUNTAIN_STEPS = [
  { title: '1. Air climbs', text: 'Wind pushes moist air uphill. Air pressure drops, so the rising air expands and cools.' },
  { title: '2. A cloud can grow', text: 'If the air cools enough to become saturated, a cloud can form. Enough moisture and growing droplets or ice crystals can produce rain or snow.' },
  { title: '3. Air descends', text: 'Air sinking on the other side compresses and warms. Its relative humidity falls, so clouds can shrink and the sheltered slope may receive less precipitation.' },
] as const;
