import type { ScienceQuestion, ScienceTopicId } from '../domain/science';

type Item = Omit<ScienceQuestion, 'topicId'>;
function q(id: string, standard: string, prompt: string, choices: string[], answer: number | number[], hint: string, explanation: string): Item {
  return { id, standard, prompt, choices, answer: typeof answer === 'number' ? [answer] : answer, kind: typeof answer === 'number' ? 'single' : 'multiple', hint, explanation };
}
function trail(topicId: ScienceTopicId, items: Item[]): ScienceQuestion[] {
  return items.map(item => ({ ...item, topicId, id: `${topicId}:${item.id}` }));
}

export const SCIENCE_QUESTIONS: readonly ScienceQuestion[] = [
  ...trail('watersheds', [
    q('land', '4.8a', 'Which description includes the whole watershed of a creek?', ['Only the water inside the creek', 'All the land draining surface water to the creek’s outlet', 'Only the trees touching the creek', 'Every place in Virginia'], 1, 'Think about where rain travels before it reaches the creek.', 'A watershed includes the land that drains surface water to a shared outlet. Streets, fields, and forests can all be part of it.'),
    q('james', '4.8a', 'Runoff enters a tributary of the James River. Which larger body of water is downstream of the James?', ['Lake Drummond', 'The New River', 'The Chesapeake Bay', 'The Ohio River'], 2, 'Follow the James toward Virginia’s coast.', 'The James River empties into the Chesapeake Bay. Pollution in its tributaries can therefore affect the Bay as well as local streams.'),
    q('drain', '4.8a', 'A student sees litter beside a storm drain before rain. What is the best explanation of the risk?', ['Runoff may carry it to a stream connected to the drain', 'All storm drains clean water before releasing it', 'Litter stays in place whenever rain falls', 'Only people living beside the ocean can affect coastal water'], 0, 'A storm drain can connect a street with a waterway.', 'Runoff can carry litter into drains and connected waterways. Caring for land upstream helps protect water downstream.'),
    q('buffers', '4.8a', 'Which TWO actions help protect water in a watershed?', ['Leave loose soil beside a stream', 'Dump extra fertilizer into a drain', 'Keep a strip of plants beside the stream', 'Collect litter before it washes away'], [2, 3], 'Choose actions that keep sediment or waste out of flowing water.', 'Streamside plants slow runoff and help trap sediment. Collecting litter prevents it from being carried into waterways; dumping fertilizer and exposing soil increase pollution risks.'),
    { ...q('route', '4.8a', 'Put this model raindrop’s journey in order, starting on land.', ['Chesapeake Bay', 'Rain runs off a hillside', 'James River', 'A small tributary stream'], [1, 3, 2, 0], 'Start at the hillside, then follow connected waterways toward the coast.', 'In this model, water runs from the hillside into a tributary, then the James River, and finally the Chesapeake Bay. Some real rainwater also soaks into the ground.'), kind: 'order' },
    q('new', '4.8a', 'A map shows the New River flowing north out of Virginia. What can you conclude?', ['The map must be upside down', 'All Virginia rivers flow to the Chesapeake Bay', 'Water can flow north when the land slopes downhill that way', 'Gravity pulls all rivers toward the south'], 2, 'Downhill is a change in elevation, not a compass direction.', 'Gravity moves water downhill. The New River can flow north because its downstream channel is lower; it belongs to a river system that eventually reaches the Mississippi.'),
  ]),
  ...trail('chesapeake', [
    q('estuary', '4.7b', 'Why is the Chesapeake Bay an estuary?', ['Its water never moves', 'It contains only freshwater', 'It contains no plants', 'Fresh river water mixes with salty ocean water there'], 3, 'Think about the two water sources meeting at the coast.', 'An estuary is a coastal mixing area for fresh and salt water. This creates brackish conditions that can vary across the Bay.'),
    { ...q('salinity', '4.7b', 'Which sample has the greatest salinity?', ['Sample A', 'Sample B', 'Sample C', 'They are equal'], 2, 'Compare the dissolved salt in the same amount of water.', 'Sample C has 20 grams of salt per liter, the greatest concentration in the table. Comparing equal volumes makes the comparison fair.'), table: { caption: 'Invented classroom samples: dissolved salt', headings: ['Sample', 'Salt (grams per liter)'], rows: [['A', '2'], ['B', '10'], ['C', '20']] } },
    q('sediment', '4.7c', 'After a storm, sediment makes Bay water cloudy. Why might underwater plants grow less?', ['Sediment always makes water warmer', 'Less sunlight reaches their leaves', 'Plants no longer need carbon dioxide', 'Cloudy water turns all plants into consumers'], 1, 'Think about the energy plants use to make food.', 'Suspended sediment can block sunlight. Underwater plants need light for photosynthesis, so less light can limit their growth.'),
    q('oyster', '4.8b', 'Which TWO statements explain the value of an oyster reef?', ['It provides habitat for other animals', 'It removes every harmful chemical', 'Oysters filter algae and particles as they feed', 'It makes salty water safe to drink'], [0, 2], 'A reef offers shelter, and oysters feed by filtering water.', 'Oyster reefs provide habitat, and oysters can improve water clarity by filtering particles and algae. This does not remove all pollution or turn Bay water into drinking water.'),
    { ...q('chain', '4.3b', 'Build this simplified food chain from producer to final consumer.', ['Blue crab', 'Algae', 'Oyster'], [1, 2, 0], 'Begin with the organism that makes food using sunlight.', 'Algae are producers. An oyster consumes algae, and a blue crab can consume an oyster. Arrows from food to eater show the direction of energy transfer.'), kind: 'order' },
    q('oxygen', '4.7c', 'An algal bloom dies and decomposes. Why can this harm fish?', ['Decomposers add unlimited oxygen', 'Dead algae stop all water movement', 'The water becomes pure freshwater immediately', 'Decomposition can use much of the dissolved oxygen fish need'], 3, 'Fish need oxygen in the water; decomposers also use oxygen.', 'Decomposers use dissolved oxygen as they break down dead algae. A large amount of decomposition can leave too little oxygen for fish.'),
  ]),
  ...trail('forests', [
    q('food', '4.2a–c', 'How does an oak tree obtain the sugars it needs?', ['Roots absorb ready-made sugar from rocks', 'Leaves use light, water, and carbon dioxide to make sugar', 'Leaves turn oxygen into soil', 'The tree must eat insects'], 1, 'Recall what plants do during photosynthesis.', 'Green plants make sugars through photosynthesis. Roots provide water and minerals, but soil is not the source of ready-made plant food.'),
    q('population', '4.3a–c', 'Which group is a population in a Virginia woodland?', ['All trees, birds, and fungi in the woodland', 'The soil, sunlight, and rain', 'All gray squirrels living in that woodland', 'Every animal species in Virginia'], 2, 'A population contains one species in one area.', 'A population is members of the same species in the same area. Different populations together form a community; nonliving surroundings are part of the ecosystem.'),
    q('talons', '4.2a–c', 'Which structure most directly helps a hawk capture and hold prey?', ['Its sharp talons', 'The minerals in nearby soil', 'The bark of a tree', 'The roots of a wildflower'], 0, 'Choose an animal body part suited to its feeding role.', 'A hawk’s sharp talons grasp prey. This connects an animal’s physical structure with a function that helps it obtain food and survive.'),
    q('benefits', '4.8d', 'Which TWO are benefits of keeping healthy trees beside a stream?', ['They stop every flood', 'They make new coal each spring', 'Their roots help hold soil in place', 'They provide habitat and shade'], [2, 3], 'Think about tree roots and the living space around the branches.', 'Roots help reduce soil erosion, and trees provide shade and habitat. They do not prevent every flood and cannot replace coal on a human timescale.'),
    q('decomposer', '4.3a–c', 'Fungi break down a fallen tree. What important role are they playing?', ['Making sunlight for producers', 'Returning nutrients by decomposing dead matter', 'Turning all nutrients into energy that disappears', 'Preventing any future plant growth'], 1, 'Think about what happens to the materials in a dead organism.', 'Decomposers break down dead matter and return nutrients to the environment. Plants can use nutrients again, while energy flows through the ecosystem.'),
    q('regrow', '4.8b', 'A class says a forest can supply wood forever as long as one seed is planted. What is the best response?', ['One seed replaces a whole forest immediately', 'Trees cannot regrow', 'Wood is made from coal', 'Regrowth, harvesting rate, and habitat protection all matter'], 3, 'Compare how quickly wood is used with how quickly trees grow.', 'Trees can regrow, but a seed does not immediately replace a mature forest. Responsible management considers harvest rates, successful regrowth, water, and wildlife habitat.'),
  ]),
  ...trail('soil', [
    q('mixture', '4.8d', 'Which description best explains why soil is an important natural resource?', ['It is only crushed rock with no living things', 'It supplies every plant with sunlight', 'It supports plants and contains particles, organic matter, air, and water', 'It forms instantly whenever land is cleared'], 2, 'Consider both what is in soil and what soil supports.', 'Soil includes mineral particles, organic material, water, air, and organisms. It supports plant growth, so protecting it supports food, forests, and habitats.'),
    q('weathering', '5.8d', 'Water freezes in a crack and breaks a rock apart. Which process happened?', ['Deposition', 'Weathering', 'Erosion by wind', 'Photosynthesis'], 1, 'Has the rock broken in place, or has sediment been transported?', 'Breaking rock in place is weathering. Transporting the pieces is erosion; dropping them in a new place is deposition.'),
    q('deposition', '5.8d', 'A stream slows down and leaves sand along its bank. What is happening?', ['Deposition', 'Photosynthesis', 'Melting', 'Pollination'], 0, 'The key clue is that transported material is being left behind.', 'Deposition occurs when transported material settles or is dropped. The water first carried the sand through erosion, then deposited it as it slowed.'),
    { ...q('sequence', '5.8d', 'Order the processes in this story of a rock fragment.', ['The fragment settles on a riverbank', 'Rock cracks into smaller fragments', 'Flowing water carries a fragment away'], [1, 2, 0], 'Use the pattern break, move, then drop.', 'The rock first weathers into fragments. Erosion moves a fragment, and deposition leaves it on the bank. These are connected but distinct processes.'), kind: 'order' },
    q('cover', '4.8d', 'Which TWO choices help a farm protect soil and nearby water?', ['Leave fields bare during heavy rain', 'Plant cover crops between harvests', 'Keep vegetation beside streams', 'Push loose soil into the stream'], [1, 2], 'Choose ways to hold soil in place and slow runoff.', 'Cover crops and streamside vegetation help hold soil and reduce sediment reaching streams. Bare soil and dumping material into water do the opposite.'),
    q('pavement', '4.8d', 'A grassy area becomes a paved parking lot. What change should planners investigate?', ['More tree roots will grow through the pavement immediately', 'Rain will stop falling on that land', 'The lot will make an unlimited supply of freshwater', 'Less water may soak into the ground and more may run off'], 3, 'Compare how water enters grass-covered soil and pavement.', 'Pavement blocks much infiltration, so more rain may become surface runoff. Planners can consider rain gardens, trees, and other ways to manage that water.'),
  ]),
  ...trail('rocks', [
    q('aggregate', '4.8c', 'Why are sand and gravel valuable resources in Virginia?', ['They are food for all forest animals', 'They can be used to build roads and make concrete', 'They replace sunlight in photosynthesis', 'They are all fossil fuels'], 1, 'Connect the properties of small rock particles with construction.', 'Sand and gravel are construction materials used in concrete and roads. They are resources because their properties make them useful to people.'),
    q('igneous', '5.8c', 'Molten material cools and solidifies. What type of rock forms?', ['Sedimentary', 'Metamorphic', 'Igneous', 'Soil only'], 2, 'The clue is cooling from a melted state.', 'Igneous rock forms when molten material cools and solidifies. Metamorphic rock changes without melting; many sedimentary rocks form from accumulated sediment.'),
    q('metamorphic', '5.8c', 'Which process can form metamorphic rock?', ['Heat and pressure change existing rock without melting it', 'A tree takes in carbon dioxide', 'Sand washes down a stream but stays loose', 'Molten rock cools into a solid'], 0, 'Metamorphic change happens to rock that stays solid.', 'Heat and pressure can alter solid rock into metamorphic rock. Melting followed by cooling produces igneous rock instead.'),
    q('fossil', '5.8e', 'Marine shell fossils are found in rock now on dry land. Which inference is best supported?', ['The shells prove people carried all of the rocks there', 'The land will be underwater tomorrow', 'The rock formed from a modern parking lot', 'The area had a marine environment in the past'], 3, 'Use the kind of organism preserved as evidence of an earlier habitat.', 'Marine fossils support the inference that the material formed in an environment containing marine life. The fossils alone do not predict tomorrow’s conditions or give an exact age.'),
    q('plates', '5.8a–b', 'What helped build the Appalachian Mountains over geologic time?', ['Trees lifting the crust with their roots', 'Large plates moving and colliding', 'The Moon pulling every rock upward each day', 'One recent rainstorm'], 1, 'Think about movement driven by Earth’s internal energy.', 'Past plate movement and collisions helped form the Appalachians. Earth’s internal heat helps drive plate motion over very long periods.'),
    q('uses', '4.8c', 'Which TWO pairs correctly connect a Virginia resource with a use?', ['Coal — fuel and steelmaking', 'Granite — food for oysters', 'Limestone — crushed stone for construction', 'Sand — an unlimited source of freshwater'], [0, 2], 'Match each material with a use based on its properties.', 'Virginia coal is used for fuel and in steelmaking, while limestone supplies stone for construction. Granite is not food, and sand does not create water.'),
  ]),
  ...trail('energy', [
    q('renewable', '5.9a', 'Which TWO energy sources are renewable?', ['Coal', 'Sunlight', 'Natural gas', 'Wind'], [1, 3], 'Look for sources replenished by ongoing natural processes.', 'Sunlight and wind are replenished naturally. Coal and natural gas take far too long to form to replace what people use on human timescales.'),
    q('gas', '5.9a', 'Why is natural gas classified as nonrenewable?', ['Anything underground is renewable', 'Its name includes “natural”', 'People use it much faster than it forms', 'It cannot be used for energy'], 2, 'Classification depends on replacement time, not the name.', 'Natural gas is a fossil fuel that forms over very long periods. People consume it far faster than nature replaces it, making it nonrenewable.'),
    q('solar', '5.2a–d', 'What energy transformation occurs in a solar panel generating electricity?', ['Radiant energy becomes electrical energy', 'Electrical energy becomes new matter', 'Sound energy becomes coal', 'Energy is created from nothing'], 0, 'A solar panel receives light and supplies electrical energy.', 'A solar panel transforms radiant energy from sunlight into electrical energy. The panel does not create energy from nothing.'),
    { ...q('hydro', '5.2a–d', 'Put this hydroelectric energy path in order.', ['A lamp gives off light and heat', 'Moving water turns a turbine', 'A generator supplies electrical energy'], [1, 2, 0], 'Start with moving water and follow the transformations to the lamp.', 'Moving water turns a turbine, a generator converts motion into electrical energy, and the lamp transforms electricity into light and heat.'), kind: 'order' },
    q('tradeoff', '5.9a', 'A community studies a proposed hydroelectric dam. Which comparison is most useful?', ['Whether dams make new water from nothing', 'Whether all fish prefer the same water depth', 'Whether renewable means there can be no habitat change', 'Electricity benefits and possible changes to river habitats'], 3, 'A renewable source can still involve environmental tradeoffs.', 'Moving water is renewable, but dams can change flow and habitat. Good decisions consider both energy benefits and effects on the river.'),
    q('lamp', '5.2a–d', 'A lamp gives off light and becomes warm. What happened to the electrical energy?', ['All of it disappeared', 'It changed into light and thermal energy', 'It turned the lamp into a fossil fuel', 'Only the light contains energy'], 1, 'Account for both the visible light and the warmth.', 'Electrical energy is transformed into radiant and thermal energy. Energy is conserved even when some spreads into the surroundings as heat.'),
  ]),
  ...trail('conservation', [
    q('reuse', '5.9b', 'Which action is reuse?', ['Throwing away a bottle after one drink', 'Processing scrap metal into a new product', 'Refilling the same durable water bottle', 'Buying extra packaging'], 2, 'Reuse keeps the item in service without turning it into new material.', 'Refilling a durable bottle uses the same item again. Recycling involves processing used material into material for another product.'),
    q('shower', '5.9b', 'Why can a shorter warm shower conserve more than one resource?', ['It saves water and reduces energy used to heat water', 'It creates new coal and water', 'It stops the water cycle', 'It makes all electricity renewable'], 0, 'Think about the water and what warms it.', 'A shorter warm shower can use less water and less energy for water heating. One action can therefore conserve both water and energy resources.'),
    { ...q('lamps', '5.9c', 'Both lamps give the same useful light for one hour. Which conclusion is supported?', ['Lamp A uses less energy', 'Lamp B uses 50 fewer watt-hours', 'Lamp B creates energy', 'The lamps use equal energy'], 1, 'Compare energy use for the same job and the same time.', 'Lamp B uses 10 watt-hours while Lamp A uses 60. The difference is 50 watt-hours. Equal useful light and time support an efficiency comparison.'), table: { caption: 'Invented classroom comparison: same light for one hour', headings: ['Lamp', 'Energy used (watt-hours)'], rows: [['A', '60'], ['B', '10']] } },
    q('community', '5.9b', 'Which TWO community actions can conserve resources?', ['Keeping empty buildings fully lit all night', 'Replacing every tree with pavement', 'Providing shared public transportation', 'Providing collection for accepted recyclable materials'], [2, 3], 'Choose actions that reduce fuel or new-material demand.', 'Public transportation can reduce fuel use per traveler, and recycling can reduce the need for newly extracted material. Both require thoughtful planning and participation.'),
    q('insulation', '5.9c', 'How does insulation help a heated building use less energy in winter?', ['It creates unlimited thermal energy', 'It changes every energy source into sunlight', 'It slows heat transfer from inside to outside', 'It makes the outdoor air stop moving'], 2, 'The goal is to keep useful warmth inside longer.', 'Insulation slows heat transfer through the building. The heating system then needs less energy to maintain the same indoor conditions.'),
    q('conserved', '5.2a–d', 'Which statement correctly explains energy conservation?', ['An efficient lamp destroys unused energy', 'Turning off a light removes energy from the universe', 'Energy can only exist as electricity', 'We can use fewer energy resources even though energy itself is not destroyed'], 3, 'Distinguish careful resource use from the scientific law about energy.', 'Everyday conservation reduces resource use and waste. The scientific principle says energy is transferred or transformed, not created or destroyed.'),
  ]),
  ...trail('investigations', [
    q('testable', '4.1', 'Which question can be investigated with measurements?', ['Which river is the prettiest?', 'Does mulch change the mass of soil washed from a tray?', 'Which rock color is the nicest?', 'Is a forest more fun than a beach?'], 1, 'Find a question with a change and an observable or measurable result.', 'Comparing soil loss with and without mulch is testable through measurements. The other questions ask about personal preferences.'),
    q('variable', '5.1', 'Students change only the amount of ground cover and measure soil loss. What is the independent variable?', ['The amount of ground cover', 'The measured soil loss', 'The label on the table', 'The conclusion after the test'], 0, 'The independent variable is deliberately changed.', 'Ground cover is the independent variable because students change it. Soil loss is the dependent variable because it is the measured outcome.'),
    q('constants', '5.1', 'Students compare a bare tray with a mulched tray. Which TWO conditions should stay the same?', ['The ground cover being tested', 'The result written before testing', 'The tray slope', 'The amount of water poured'], [2, 3], 'Keep other causes of soil loss alike while changing the cover.', 'Slope and water amount can affect soil loss. Keeping them alike makes it easier to investigate the effect of ground cover.'),
    { ...q('evidence', '5.1', 'Which claim is best supported by these model results?', ['Mulch stopped all erosion', 'Every real hillside will lose exactly 4 grams', 'The bare tray always lost less soil', 'The mulched tray lost less soil in every trial'], 3, 'Compare the two treatments within each trial without claiming more than the data show.', 'The mulched tray lost 4, 3, and 5 grams; the bare tray lost 18, 20, and 19. Mulch reduced soil loss in these trials, but did not eliminate it or prove all real hillsides behave identically.'), table: { caption: 'Invented fair-test data: soil washed away', headings: ['Trial', 'Bare soil (g)', 'Mulched soil (g)'], rows: [['1', '18', '4'], ['2', '20', '3'], ['3', '19', '5']] } },
    q('tool', '4.1', 'Which tool should students use to measure the mass of dried soil collected after runoff?', ['A thermometer', 'A balance', 'A compass', 'A clock'], 1, 'Match the tool with mass, not volume or temperature.', 'A balance measures mass, which can be recorded in grams. A thermometer measures temperature, a compass direction, and a clock time.'),
    { ...q('design', '5.1', 'Order these engineering steps for a model stream-bank protector.', ['Use results to improve the design', 'Set a goal and choose a design', 'Build and test the model'], [1, 2, 0], 'Decide what success means before testing and improving.', 'Engineers define a goal and design, build and test a model, and use evidence to improve it. They can repeat this cycle and must consider the model’s limitations.'), kind: 'order' },
  ]),
];
