import type { MissionId } from "../domain/mission";
import type { MissionChallenge } from "./missionActivities";

export interface PracticeTrail {
  id: string;
  title: string;
  lesson: string;
  questions: readonly MissionChallenge[];
}
function q(prompt: string, correct: string, other: [string, string, string], explanation: string): MissionChallenge {
  const answer = Array.from(prompt).reduce((sum, letter) => sum + letter.charCodeAt(0), 0) % 4;
  const choices = [...other];
  choices.splice(answer, 0, correct);
  return { prompt, choices, answer, clue: explanation, explanation };
}
function trail(id: string, title: string, lesson: string, questions: MissionChallenge[]): PracticeTrail {
  return { id, title, lesson, questions };
}

/** Original questions, not copied SOLpass or official released assessment items.
 * Reviewed against the SOLpass 2023 Virginia Studies guides in September 2026.
 * IDs are stable because practice progress is separate from mission badges.
 */
export const SOL_PRACTICE: Record<MissionId, readonly PracticeTrail[]> = {
  "VS.1": [
    trail("regions", "Read the landscape", "East to west: Coastal Plain (Tidewater), Piedmont, Blue Ridge Mountains, Valley and Ridge, then Appalachian Plateau. The Fall Line separates the low Coastal Plain from the rolling Piedmont. Old, rounded Blue Ridge mountains give way to long valleys and ridges. A plateau is high land with a relatively flat top.", [
      q("Your postcard shows rolling hills west of the Fall Line. Which region fits?", "Piedmont", ["Coastal Plain", "Appalachian Plateau", "Eastern Shore"], "The Piedmont has rolling hills between the Coastal Plain and Blue Ridge."),
      q("You travel west of the Blue Ridge into long valleys between ridges. Where are you?", "Valley and Ridge", ["Coastal Plain", "Piedmont", "Eastern Shore"], "Valley and Ridge lies west of the Blue Ridge and includes the Great Valley of Virginia."),
      q("Which region reaches into southwestern Virginia and has elevated, fairly flat land?", "Appalachian Plateau", ["Coastal Plain", "Chesapeake Bay", "Piedmont"], "A plateau has a relatively flat top. A small part of the Appalachian Plateau lies in Virginia.")
    ]),
    trail("waterways", "Follow four rivers", "Match Alexandria with the Potomac, Fredericksburg with the Rappahannock, Yorktown with the York, and Richmond and Jamestown with the James. These rivers flow toward the Chesapeake Bay. The bay offered food, sheltered harbors, and travel; the Atlantic connected Virginia with Europe, Africa, and the Caribbean.", [
      q("A traveler pairs Alexandria with the James River. Which correction belongs on the map?", "Alexandria — Potomac", ["Alexandria — York", "Alexandria — Rappahannock", "Alexandria — New"], "Alexandria is on the Potomac. Richmond and Jamestown belong with the James."),
      q("Which river-and-town card is matched correctly?", "Fredericksburg — Rappahannock", ["Yorktown — Potomac", "Richmond — York", "Jamestown — Rappahannock"], "Fredericksburg is on the Rappahannock; Yorktown is on the York. River names help connect your visits."),
      q("Which water route linked colonial Virginia directly with Europe and Africa?", "Atlantic Ocean", ["Lake Drummond", "Dismal Swamp", "A mountain spring"], "Ships crossed the Atlantic. Rivers and the Chesapeake Bay connected inland settlements with this ocean route.")
    ]),
    trail("borders", "Find Virginia’s neighbors", "Virginia borders Maryland, West Virginia, Kentucky, Tennessee, and North Carolina, and meets Washington, D.C. The Chesapeake Bay separates the Eastern Shore peninsula from mainland Virginia. A peninsula has water on three sides. Lake Drummond is a shallow natural lake in the Great Dismal Swamp in the Coastal Plain.", [
      q("Which state belongs on Virginia’s border puzzle?", "Kentucky", ["Pennsylvania", "South Carolina", "Ohio"], "Kentucky touches Virginia on the west. Virginia has five neighboring states."),
      q("Water surrounds the Eastern Shore on three sides. Which word describes this land?", "Peninsula", ["Plateau", "Mountain ridge", "Island"], "A peninsula has water on three sides; an island has water all around it."),
      q("A journal describes Lake Drummond in the Great Dismal Swamp. Which region fits?", "Coastal Plain", ["Blue Ridge", "Valley and Ridge", "Appalachian Plateau"], "Lake Drummond and the Great Dismal Swamp are in the Coastal Plain near the Hampton Roads region.")
    ])
  ],
  "VS.2": [
    trail("languages", "Listen to different nations", "Prominent language families around 1600 included Algonquian in Tidewater, Siouan in the Piedmont, and Iroquoian in southwestern Virginia and near the Dismal Swamp. Powhatan languages are Algonquian; Monacan is Siouan; Cherokee and Nottoway languages are Iroquoian. A language family is not a single tribe or a single culture.", [
      q("A Monacan exhibit describes a language spoken in the Piedmont. Which family connects the clues?", "Siouan", ["Algonquian", "Iroquoian", "Latin"], "Monacan people spoke a Siouan language. Virginia’s Indigenous nations did not all speak one language."),
      q("Which language family connects with Powhatan peoples in Tidewater?", "Algonquian", ["Siouan", "Iroquoian", "Spanish"], "Algonquian languages were prominent in the Coastal Plain. Related languages do not make different nations identical."),
      q("Why might a museum group Cherokee and Nottoway language displays together?", "Their languages belong to the Iroquoian family", ["They are the same nation", "Neither had a government", "Both originated in Europe"], "Cherokee and Nottoway languages belong to the Iroquoian family, while their communities have distinct histories.")
    ]),
    trail("communities", "Read land and community clues", "Werowocomoco was a Powhatan political and spiritual center on the York River. Archaeologists study artifacts and where they were found; Indigenous knowledge helps interpret the past. Rivers supported farming, fishing, and travel. People used wood, bark, stone, and animal materials and adapted to seasons. Tribal nations continue today with their own governments, cultures, and changing lives.", [
      q("Why study a pottery fragment and its exact location together at Werowocomoco?", "Its context helps explain how people lived", ["Every artifact should become a souvenir", "One object tells the whole story", "Living communities have no knowledge"], "Context connects an artifact with its surroundings. Archaeology and Indigenous knowledge help explain this important Powhatan center."),
      q("Why would a community grow corn, beans, and squash near a river?", "Water, fertile soil, and travel routes support the community", ["Seasons never change there", "Rivers prevent every flood", "No other food is needed"], "Rivers supported farming, fishing, and transportation. People adapted their work to the environment and seasons."),
      q("Which museum plan best represents Indigenous Virginia today?", "Include present-day tribal voices, governments, and arts", ["End every display in 1607", "Give every nation one identical culture", "Use only English accounts"], "Living nations preserve traditions, advocate for recognition, and participate in modern life. Their own perspectives matter.")
    ])
  ],
  "VS.3": [
    trail("charter", "Plan a colony", "England sought trade, resources, markets, wealth, and power. Virginia Company investors hoped for profits. King James I’s 1606 charter authorized an English colony and promised colonists English rights. Jamestown began in 1607 beside the James River as the first permanent English settlement in North America. Deep water suited ships, but unsafe drinking water and disease made the location risky.", [
      q("An investor pays for a Virginia Company voyage. What is the investor hoping for?", "Profits from resources and trade", ["A guaranteed royal title", "An end to farming", "A school holiday"], "Investors provide money hoping to earn money later. England also wanted greater power and trade."),
      q("Which document gave the Virginia Company royal permission to establish its colony?", "The 1606 charter", ["The Bill of Rights", "The Declaration of Independence", "The Treaty of Paris"], "A charter grants authority and states rights. English permission did not erase Indigenous ownership of their lands."),
      q("Why would deep river water attract Jamestown’s planners?", "Large ships could approach the settlement", ["It guaranteed safe drinking water", "It stopped every disease", "It made farming unnecessary"], "Deep water helped ships dock and trade. That advantage did not solve the settlement’s drinking-water and health problems.")
    ]),
    trail("survival", "Solve a survival problem", "English settlers entered Powhatan homelands. Trade with Powhatan communities supplied food and knowledge, while conflict also shaped relations. John Smith organized work. Private land ownership and farming changed the colony; John Rolfe’s commercially successful tobacco helped it earn money. No single person or crop solved every danger.", [
      q("The settlement is short of food. Which exchange helped colonists survive?", "Trading with Powhatan communities", ["Waiting for railroads", "Buying from a modern supermarket", "Shipping every crop away"], "Powhatan trade and knowledge helped sustain the colony. Relations also involved conflict and pressure on Indigenous land."),
      q("A card says “organized work and strengthened early Jamestown leadership.” Who fits?", "John Smith", ["Woodrow Wilson", "Barbara Johns", "James Monroe"], "Captain John Smith helped organize work. Many other people’s actions, including Indigenous trade, also supported survival."),
      q("Which change helped the colony earn money through trade?", "Growing tobacco successfully for sale", ["Finding large gold mines immediately", "Ending all contact with England", "Building steamships in 1607"], "John Rolfe is associated with successful commercial tobacco. Its growth increased demands for land and labor, with lasting harmful effects.")
    ]),
    trail("community", "Meet a changing community", "The General Assembly met in 1619 with the governor, council, and elected burgesses. Voting was limited to a small part of the population. Captive Africans from present-day Angola arrived at Point Comfort near Hampton in 1619. More English women arrived in 1620, expanding families and community life; some had arrived earlier. Indigenous women already lived in Virginia.", [
      q("Colonists elect burgesses to help make laws. Which idea are they practicing?", "Representative government", ["Rule by inheritance alone", "Every person voting on every law", "Government without laws"], "Elected representatives act for their voters. The 1619 assembly did not give equal participation to women, enslaved people, or everyone else."),
      q("Which field-trip area connects with captive Africans arriving at Point Comfort in 1619?", "Hampton", ["High Bridge", "Appomattox", "Harpers Ferry"], "Point Comfort is near today’s Fort Monroe. Africans brought skills and cultures despite forced transportation and loss of freedom."),
      q("Why did more English women arriving in 1620 matter to Jamestown?", "They helped expand families and a lasting community", ["No women had ever lived in Virginia", "All women immediately gained voting rights", "Slavery ended"], "The colony became a more permanent community. Indigenous women lived in Virginia long before it, and some English women arrived before 1620.")
    ])
  ],
  "VS.4": [
    trail("market", "Run a colonial market", "Tobacco was a cash crop grown to sell. People used barter (direct exchange), credit (paying later), and debt (something owed), since coins were scarce. Germans and Scots-Irish settled especially in the Shenandoah Valley. Many English settlers and forcibly transported Africans lived in Tidewater and the Piedmont. Diverse communities influenced food, buildings, music, and place names.", [
      q("A shoemaker exchanges a repair for apples. What kind of trade is this?", "Barter", ["Taxation", "Credit", "Interest"], "Barter directly exchanges goods or services. The repair is a service and the apples are goods."),
      q("A farmer receives tools today and promises payment after harvest. What is the store extending?", "Credit", ["A gift", "A vote", "A charter"], "Credit allows payment later. The unpaid amount is a debt the farmer owes."),
      q("Which pairing fits a major colonial settlement pattern?", "Germans and Scots-Irish — Shenandoah Valley", ["All Europeans — Appalachian Plateau only", "All Indigenous people — one town", "All Africans — northern mountains only"], "The Shenandoah Valley was a migration route and home to many German and Scots-Irish immigrants.")
    ]),
    trail("labor-laws", "Investigate labor and law", "Indentures required labor for a fixed term, often to pay passage costs. Racial slavery developed through laws that treated people as property for life and passed enslaved status from mother to child. Africans were forcibly transported through the transatlantic slave trade. In 1699, the capital moved from Jamestown to Williamsburg after fire and amid concerns about unhealthy conditions.", [
      q("Which difference belongs in a comparison of indentured servitude and racial slavery?", "Indentures had a set term; slavery was generally lifelong and hereditary", ["Both guaranteed release after four years", "Enslaved people freely chose contracts", "Neither system involved labor"], "Indentures ended after an agreed term. Slavery laws denied freedom and made status inheritable. Both systems could involve harsh treatment."),
      q("A law makes a child’s enslaved status follow the mother’s. What does this show?", "Law helped make slavery hereditary", ["Slavery ended each generation", "Everyone received equal rights", "Children elected colonial leaders"], "Hereditary means passed from parent to child. Lawmakers deliberately built and enforced Virginia’s racial slavery system."),
      q("After a statehouse fire and concerns about unhealthy conditions, which move followed in 1699?", "Jamestown to Williamsburg", ["Richmond to Norfolk", "Williamsburg to Yorktown", "Jamestown to Appomattox"], "Williamsburg became the new capital. The later move to Richmond belongs to the Revolutionary era.")
    ])
  ],
  "VS.5": [
    trail("voices", "Choose a Revolutionary role", "Many colonists objected to taxation by a Parliament where they had no elected representatives. Jefferson was the Declaration’s principal author; Washington commanded the Continental Army. Patriots supported independence, Loyalists supported Britain, and others stayed neutral. Women, Indigenous people, and free and enslaved Black people made varied choices under unequal conditions.", [
      q("A colonist protests taxes passed by distant lawmakers the colony did not elect. What is the complaint?", "Taxation without representation", ["Too many colonial votes in Parliament", "A shortage of mountain passes", "The absence of a royal army"], "Many colonists argued that Parliament taxed them without an elected voice. This helped drive the independence movement."),
      q("Which task belongs with George Washington during the Revolution?", "Commanding the Continental Army", ["Writing every colonial newspaper", "Serving as British king", "Leading the Confederate army"], "Washington led the Continental Army. Jefferson was the Declaration of Independence’s principal author."),
      q("One neighbor supports independence and another supports Britain. Which labels fit?", "Patriot and Loyalist", ["Both Patriots", "Both neutral", "Governor and burgess"], "Patriots supported independence; Loyalists supported Britain. Other people remained neutral, and choices could change.")
    ]),
    trail("yorktown", "Uncover Yorktown’s connections", "James Armistead Lafayette gathered intelligence for the American side while enslaved and later gained freedom. American and French troops and French naval power trapped Cornwallis at Yorktown in 1781. Richmond became Virginia’s capital in 1780 because it was more central and farther from coastal attack. The 1783 peace treaty recognized independence.", [
      q("Which caption belongs beside James Armistead Lafayette at a Yorktown exhibit?", "A spy whose information aided the American side", ["British king", "Confederate commander", "Author of the Constitution"], "James Armistead Lafayette supplied valuable intelligence while enslaved. His story connects individual action with Yorktown."),
      q("Why was the French navy important at Yorktown?", "It blocked British escape by sea", ["It built High Bridge", "It wrote the Declaration", "It moved the capital to Jamestown"], "French naval power and allied land forces worked together to trap Cornwallis. Yorktown connects Virginia with an international alliance."),
      q("Why choose Richmond as Virginia’s capital in 1780?", "It was inland and more central", ["It was closer to the exposed coast", "It had no river connection", "It was already the national capital"], "Richmond was farther from coastal attacks and more central to Virginia’s population, although it was not immune from attack.")
    ])
  ],
  "VS.6": [
    trail("founders", "Match people to ideas", "Washington became the first U.S. president and is called the Father of Our Country. Madison’s work on the Constitution earned him the title Father of the Constitution. Patrick Henry urged resistance to British rule in a famous 1775 speech. George Mason wrote the Virginia Declaration of Rights. Jefferson drafted the Virginia Statute for Religious Freedom, enacted in 1786.", [
      q("Who belongs beside the label “Father of the Constitution”?", "James Madison", ["John Smith", "John Rolfe", "Robert E. Lee"], "Madison helped shape the Constitution and kept detailed convention notes. Washington is called the Father of Our Country."),
      q("Which George Mason document influenced the U.S. Bill of Rights?", "Virginia Declaration of Rights", ["Monroe Doctrine", "Treaty of Paris", "Emancipation Proclamation"], "Mason’s 1776 Virginia Declaration of Rights influenced later statements of rights, including the U.S. Bill of Rights."),
      q("Who urged resistance in the speech remembered for “Give me liberty or give me death”?", "Patrick Henry", ["Woodrow Wilson", "James Monroe", "John Tyler"], "Patrick Henry used speeches to urge resistance to British rule. He later served as Virginia’s first elected governor.")
    ]),
    trail("government", "Build a government", "Jefferson’s religious-freedom statute protected the choice of religious belief. Founding documents influenced later protections, though slavery and unequal rights persisted. Representative democracy elects people to make decisions. Local, state, and national governments serve different communities. The Constitution’s Preamble explains its purposes; Constitution Day marks the September 17, 1787 signing.", [
      q("A law says government must not force support for a particular religion. Which document connects?", "Virginia Statute for Religious Freedom", ["A tobacco receipt", "A military surrender", "A royal tax bill"], "Jefferson drafted the statute, enacted in 1786. It helped establish religious freedom and influenced national protections."),
      q("Which action is an example of representative democracy?", "Citizens elect lawmakers to act for them", ["A ruler inherits every office", "A family chooses dinner", "A court cancels all elections"], "Representatives are chosen by voters. Local, state, and national government each have roles."),
      q("A class reads the Constitution’s Preamble. What are they reading?", "An introduction explaining the government’s purposes", ["A list of every president", "A river map", "A peace treaty with France"], "A preamble introduces a document. The Constitution’s Preamble explains why the new framework of government was established.")
    ]),
    trail("movement", "Follow movement and resistance", "Mountain gaps and valleys guided westward travel; canals, steamboats, and railroads changed transportation. Some families sought land or jobs. Enslaved people were often forced west through sale or removal, separating families; Indigenous peoples faced dispossession. In Southampton County in 1831, Nat Turner led a rebellion against slavery. Authorities suppressed it and imposed harsher restrictions on Black people.", [
      q("Why might a westward traveler choose a mountain gap?", "It offers a lower route through a mountain barrier", ["It avoids every river forever", "It guarantees free land", "It prevents all conflict"], "Gaps and valleys provided practical routes. New transportation technology changed how people and goods moved."),
      q("A map shows free settlers and enslaved people moving west. Which question prevents a misleading story?", "Did everyone travel willingly?", ["Did everyone use airplanes?", "Did geography stop mattering?", "Did every traveler become wealthy?"], "Some moved for opportunity, while enslaved people were often forced to move. Expansion also displaced Indigenous communities."),
      q("What followed the suppression of Nat Turner’s 1831 rebellion?", "Harsher restrictions on enslaved and free Black people", ["Immediate emancipation throughout Virginia", "The founding of Jamestown", "The end of racial discrimination"], "Turner resisted slavery through rebellion. Violence and tighter controls followed, exposing the conflict between slavery and freedom.")
    ])
  ],
  "VS.7": [
    trail("division", "Trace division and escape", "John Brown’s failed 1859 armory raid at Harpers Ferry sought to help overthrow slavery and deepened tensions. Slavery was central to Southern secession. The Underground Railroad was a network of helpers and safe places, not tracks; Harriet Tubman helped people escape. Disagreement over secession divided Virginia, and West Virginia became a state in 1863.", [
      q("Which purpose connects John Brown with the Harpers Ferry armory?", "Obtaining weapons for an uprising against slavery", ["Starting a tobacco market", "Signing the Constitution", "Building the first railroad"], "An armory stores weapons. Brown’s raid failed but intensified conflict over slavery; Harpers Ferry was then in Virginia."),
      q("A story calls Harriet Tubman a conductor. What sort of route did she help people follow?", "A secret escape network of helpers and safe places", ["An ordinary paid train route", "A public battlefield tour", "A colonial shipping schedule"], "The Underground Railroad was not a literal railroad. Tubman helped people escape enslavement through dangerous journeys."),
      q("Why does an 1864 map show West Virginia separately from Virginia?", "West Virginia became a state during the Civil War in 1863", ["Virginia moved to another continent", "Every Virginian supported secession", "The Revolution split the state in 1781"], "Western Unionists helped create West Virginia amid disagreement over secession. Views within both parts of Virginia were varied.")
    ]),
    trail("battles", "Connect battlefield clues", "First Manassas (Bull Run) in 1861 was an early major Confederate victory; Thomas “Stonewall” Jackson gained his nickname there. The Union USS Monitor fought the Confederate CSS Virginia in Hampton Roads in 1862. Richmond was the Confederate capital. Lee surrendered the Army of Northern Virginia to Grant at Appomattox on April 9, 1865; other armies surrendered later.", [
      q("Which pair belongs in an ironclad exhibit near Norfolk and Hampton?", "USS Monitor and CSS Virginia", ["Mayflower and Susan Constant", "Titanic and Carpathia", "Two railroad locomotives"], "Ironclads were warships protected with iron armor. The Monitor and Virginia fought in Hampton Roads in 1862."),
      q("First Manassas is linked with which Confederate general’s nickname?", "Thomas “Stonewall” Jackson", ["George Washington", "Woodrow Wilson", "John Mercer Langston"], "Jackson gained his nickname at First Manassas in 1861, an early major battle of the Civil War."),
      q("Which caption correctly describes the Appomattox meeting?", "Lee surrendered his army to Grant in April 1865", ["Cornwallis surrendered to Washington in 1865", "Every Confederate army surrendered at once", "The Civil War began there in 1859"], "Lee surrendered the Army of Northern Virginia. Sailor’s Creek and High Bridge connect with the retreat leading to Appomattox.")
    ]),
    trail("service", "Discover different kinds of service", "Virginia-born people served on different sides. Winfield Scott developed a Union strategy of blockade and control of the Mississippi. William Harvey Carney and Powhatan Beaty were Black Union soldiers awarded the Medal of Honor. Elizabeth Van Lew and Mary Jane Richards (often called Mary Bowser) aided Union intelligence. Enslaved people escaped to Union lines, including Baker, Mallory, and Townsend at Fort Monroe. Indigenous people’s roles and choices also varied.", [
      q("Which strategy matches Union general Winfield Scott?", "Block Southern ports and control the Mississippi", ["Move the Revolution to 1865", "Close every Northern factory", "Replace the Constitution with a charter"], "A blockade restricts supplies and trade. Scott’s plan sought to weaken the Confederacy through transportation and supply routes."),
      q("What connects William Harvey Carney and Powhatan Beaty?", "Both were Black Union soldiers awarded the Medal of Honor", ["Both wrote the Declaration", "Both were Confederate presidents", "Both founded Jamestown"], "Both received the Medal of Honor for Civil War service. Carney’s story also connects with his birthplace, Norfolk."),
      q("Which evidence challenges the idea that only battlefield commanders shaped the war?", "Union intelligence work by Elizabeth Van Lew and Mary Jane Richards", ["Only generals had names", "No civilians made choices", "Only official maps survive"], "Information could influence events as well as weapons. Details of some intelligence stories remain debated, so historians compare evidence carefully.")
    ])
  ],
  "VS.8": [
    trail("rebuilding", "Rebuild lives and communities", "War damaged bridges, railroads, farms, and businesses. Freed people sought education, work, housing, and family reunification. The Freedmen’s Bureau offered assistance including education and medical care. Black communities and teachers helped build schools for adults and children. Sharecroppers farmed another person’s land for a share of the harvest; unfair terms and debt could trap families in poverty.", [
      q("A newly freed adult attends school alongside children. Why does this fit Reconstruction?", "Freedmen’s Schools helped adults and children learn", ["Only children wanted education", "Adults were forbidden from all schools forever", "Schools only taught military strategy"], "Enslavement had denied many people educational opportunities. Communities, teachers, and the Freedmen’s Bureau supported learning."),
      q("A farmer pays rent with part of the harvest. Which system is this?", "Sharecropping", ["Voting", "Rationing", "Manufacturing"], "A sharecropper uses rented land and pays with a share of the crop. Debt and unequal contracts often kept families poor."),
      q("Which project would meet an urgent Reconstruction need?", "Repair railroads and help families find schooling", ["Build the first Jamestown fort", "Declare independence from Britain", "Prepare the 1606 charter"], "Reconstruction involved physical rebuilding and changes in citizenship, work, education, and political power after the Civil War.")
    ]),
    trail("amendments", "Unlock constitutional changes", "The 13th Amendment abolished slavery except as punishment for crime. The 14th established citizenship for people born or naturalized in the U.S. and subject to its jurisdiction, and guaranteed equal protection. The 15th barred denying voting rights because of race, color, or previous enslavement. These protections did not automatically end discrimination or give everyone the vote.", [
      q("Which amendment established citizenship and equal-protection guarantees?", "Fourteenth", ["First", "Thirteenth", "Fifteenth"], "Remember: 13 abolished slavery, 14 addressed citizenship and equal protection, and 15 protected voting rights from racial restrictions."),
      q("Which restriction does the Fifteenth Amendment forbid?", "Denying a vote because of race", ["A minimum voting age", "Choosing an election date", "Requiring a ballot"], "The amendment names race, color, and previous condition of servitude. Officials still used other barriers and violence to suppress voting."),
      q("Which evidence challenges the claim that abolition instantly ended every injustice?", "Discrimination and violence continued after the Thirteenth Amendment", ["The Constitution has a title", "Virginia has rivers", "The Revolution came earlier"], "Abolition was a major change, but equal rights still required organizing, legal challenges, and enforcement.")
    ]),
    trail("barriers", "Investigate progress and barriers", "John Mercer Langston took his seat as Virginia’s first Black U.S. House member in 1890 after a contested election. In 1896, Plessy v. Ferguson upheld racial segregation under the “separate but equal” doctrine. Jim Crow laws enforced separation and inequality. Poll taxes, discriminatory tests, and intimidation restricted voting. Segregation means enforced separation; discrimination means unfair treatment.", [
      q("Which achievement belongs to John Mercer Langston?", "Virginia’s first Black representative in the U.S. House", ["The first English king", "Commander at Yorktown", "Builder of every Virginia railroad"], "Langston took his seat in 1890 after a disputed election. His achievement did not remove all barriers faced by Black voters."),
      q("What was the effect of the 1896 Plessy v. Ferguson ruling?", "It gave legal support to racial segregation", ["It ordered immediate school integration", "It abolished slavery", "It created the General Assembly"], "Plessy upheld segregation under separate but equal. Facilities were unequal in practice; later civil-rights cases challenged this system."),
      q("A poll tax prevents a citizen from voting. Which problem does this illustrate?", "Disenfranchisement: blocking voting rights", ["Equal access for everyone", "Barter", "Westward migration"], "Poll taxes and discriminatory practices excluded many Black voters and also affected poor white voters.")
    ])
  ],
  "VS.9": [
    trail("networks", "Connect rails, ports, and jobs", "Railroads moved coal, lumber, farm products, and passengers. Southwest Virginia’s coalfields connected to markets; Richmond developed tobacco manufacturing. Norfolk and Newport News grew as ports. High Bridge’s former railway corridor is now a trail, showing changing uses of a place. Waterways and rail lines worked together.", [
      q("Why connect a southwestern coalfield with a port by rail?", "To move heavy coal to distant buyers", ["To stop every shipment", "To turn coal into food", "To remove all need for workers"], "Railroads linked inland resources with ports and buyers. These networks helped industries and cities grow."),
      q("Which city-and-industry pairing fits Virginia’s industrial growth?", "Richmond — tobacco manufacturing", ["Appomattox — ocean shipbuilding", "Norfolk — mountain coal mines", "Yorktown — Appalachian coalfields"], "Richmond developed tobacco manufacturing. Norfolk and Newport News grew as ports and maritime centers."),
      q("Walking High Bridge Trail today, which change can you investigate?", "A former railroad corridor became a recreation trail", ["An ocean became a mountain", "The Revolution became the Civil War", "A river stopped flowing in 1781"], "The same corridor has served transportation and recreation. Its geography still helps explain its history.")
    ]),
    trail("cities", "Watch communities change", "Urbanization means the growth of towns and cities. Farm machinery reduced labor needed for some tasks, while factory and service jobs attracted workers. Federal employment helped Northern Virginia grow; technology later expanded there and in Tidewater. Migration from other states and countries added skills, languages, and traditions. Families experienced these changes differently.", [
      q("A family leaves farm work for a factory job in a city. Which change does this illustrate?", "Urbanization", ["Secession", "Abolition", "Barter"], "Urban refers to cities. Employment and transportation opportunities helped attract people to growing cities."),
      q("How could a farm machine encourage some workers to move to a city?", "It made fewer workers necessary for some farm tasks", ["It guaranteed a city house", "It ended all farming", "It stopped every crop growing"], "Mechanization changed labor needs. Low crop prices and urban opportunities also encouraged some families to move."),
      q("Which explanation fits Northern Virginia’s growth?", "Federal employment and technology jobs attracted people", ["No people ever moved there", "Ocean fishing was the only cause", "Its population never changed after 1607"], "The area’s proximity to Washington, D.C., mattered. People arriving from many places also contributed knowledge and cultures.")
    ])
  ],
  "VS.10": [
    trail("homefront", "Help on the home front", "The U.S. entered World War I in 1917 and World War II in 1941. Woodrow Wilson was president during World War I. Rationing limited scarce purchases; victory gardens supplied food; scrap drives recovered materials; war bonds loaned money to the government. Hampton Roads ports and shipyards connected civilian work with military supply.", [
      q("Coupons limit how much sugar a family can buy during World War II. What is this?", "Rationing", ["Barter", "Secession", "Voting"], "Rationing controlled purchases of scarce goods and directed resources toward wartime needs."),
      q("How could growing a victory garden support the war effort?", "It supplied food and reduced pressure on other supplies", ["It ended war immediately", "It made every family a military unit", "It replaced all farms"], "Home-grown vegetables supplemented food supplies. Gardening worked alongside conservation and other civilian efforts."),
      q("Someone buys a war bond. What are they doing?", "Loaning money to the government", ["Buying an enemy ship", "Paying rent with crops", "Trading goods without money"], "A bond is a form of borrowing. War bonds helped finance the war and were different from ration coupons.")
    ]),
    trail("remembrance", "Connect service and remembrance", "Veterans have served in the armed forces. The Medal of Honor recognizes extraordinary military valor; it is not given to every veteran. Veterans Day honors those who served and falls on November 11, recalling the 1918 armistice that stopped World War I fighting. Virginians served in the military and worked in hospitals, factories, and ports.", [
      q("Which president connects Virginia’s presidential story with World War I?", "Woodrow Wilson", ["Thomas Jefferson", "James Madison", "George Washington"], "Wilson was born in Staunton and served as president from 1913 to 1921. The U.S. entered World War I in 1917."),
      q("What does a Medal of Honor display recognize?", "Extraordinary courage in military service", ["Everyone who lived during a war", "Only work as a president", "The number of ships a city owns"], "The Medal of Honor is the nation’s highest military decoration for valor. Veterans can be honored without receiving this particular award."),
      q("Why does November 11 connect with Veterans Day?", "World War I fighting stopped under an armistice on that date in 1918", ["Every war ended then", "The Constitution was signed then", "Jamestown was founded then"], "An armistice is an agreement to stop fighting. Veterans Day honors military veterans from all periods of service.")
    ])
  ],
  "VS.11": [
    trail("schools", "Follow students to the courts", "Barbara Johns helped lead the 1951 Moton student strike in Farmville. Lawyers including Oliver W. Hill represented families in Davis v. County School Board, one of the cases decided with Brown v. Board of Education in 1954. Brown ruled public-school segregation unconstitutional. Massive Resistance sought to block desegregation, including through school closures.", [
      q("How did the Farmville protest connect with a national Supreme Court decision?", "It led to the Davis case included in Brown", ["It wrote the 1606 charter", "It ended every unequal school that day", "It moved the national capital"], "Students, families, and lawyers linked local action with a national legal challenge. The Davis case became part of Brown."),
      q("Who belongs on the lawyer card in the school-desegregation story?", "Oliver W. Hill, Sr.", ["John Rolfe", "Cornwallis", "James Monroe"], "Oliver Hill represented families challenging school segregation. Barbara Johns helped lead the student protest."),
      q("Officials close schools to block integration. Which policy does this describe?", "Massive Resistance", ["Victory gardens", "Religious freedom", "The Reconstruction amendments"], "Massive Resistance delayed access to equal schooling. Families and communities continued fighting for education after Brown.")
    ]),
    trail("activists", "Meet change-makers", "Maggie Walker led a bank and promoted Black economic opportunity in Richmond. Robert Russa Moton worked in education. Samuel Wilbert Tucker organized a 1939 Alexandria library sit-in and pursued civil-rights law. Irene Morgan challenged segregated interstate bus travel after her 1944 arrest. Richmond-born tennis champion Arthur Ashe also advocated for civil rights.", [
      q("A display links banking, Richmond, and Black economic opportunity. Who belongs there?", "Maggie Walker", ["John Smith", "Robert E. Lee", "Patrick Henry"], "Walker connected banking and community work with economic opportunity. Civil rights include economic as well as political rights."),
      q("Which pair challenged segregation in everyday public spaces?", "Samuel Wilbert Tucker and Irene Morgan", ["Washington and Cornwallis", "Rolfe and Smith", "Monroe and Tyler"], "Tucker organized a library sit-in; Morgan challenged segregated interstate bus travel. Different actions addressed different barriers."),
      q("Why does Arthur Ashe’s story belong in the civil-rights section?", "He combined tennis achievement with advocacy for equality", ["He founded Jamestown", "He wrote the Declaration", "He commanded the Confederate navy"], "Ashe was both a champion and an advocate. Robert Russa Moton’s educational work offers another example of advancing opportunity.")
    ]),
    trail("votes", "Trace political change", "Poll taxes, tests, and discriminatory administration excluded many Black Virginians from voting. Organizing, courts, and voting helped challenge inequality. Governor A. Linwood Holton supported desegregation and sent his children to integrated schools. L. Douglas Wilder won Virginia’s 1989 gubernatorial election, becoming the nation’s first elected Black governor and taking office in 1990.", [
      q("Why study poll taxes when investigating civil rights?", "They were used to block people from voting", ["They were only for buying food", "They explain river geography", "They guaranteed equal access"], "Voting barriers excluded citizens from political participation. Civil-rights campaigns sought access to rights of citizenship."),
      q("Which action fits Governor Linwood Holton’s approach to school integration?", "Supporting integration and enrolling his children in integrated schools", ["Creating a royal charter", "Leading the Harpers Ferry raid", "Building the Jamestown fort"], "Holton’s family choices reflected his public position. Elected leaders could help advance or obstruct civil rights."),
      q("Which milestone belongs with L. Douglas Wilder’s 1989 election?", "First elected Black governor in U.S. history", ["First president born in Virginia", "First Confederate general", "First English burgess"], "Wilder won in 1989 and took office in 1990. This was a major political milestone, not the end of every barrier.")
    ])
  ],
  "VS.12": [
    trail("early", "Meet four early presidents", "Four of the first five U.S. presidents were born in Virginia: Washington (1st), Jefferson (3rd), Madison (4th), and Monroe (5th). John Adams, the 2nd, was born in Massachusetts. Washington led the Continental Army; Jefferson was the Declaration’s principal author; Madison helped shape the Constitution; Monroe is associated with the Monroe Doctrine.", [
      q("Which of the first five presidents was not born in Virginia?", "John Adams", ["George Washington", "James Madison", "James Monroe"], "Adams is the exception among the first five. The Mother of Presidents nickname counts birthplace."),
      q("Which president follows Madison in the early Virginia-born sequence?", "James Monroe", ["Woodrow Wilson", "Zachary Taylor", "William Henry Harrison"], "Monroe was fifth, following Madison, the fourth president. Jefferson was third and Washington first."),
      q("Which pairing connects a president with the right work?", "Jefferson — Declaration of Independence", ["Madison — Yorktown’s British commander", "Monroe — Jamestown’s founding", "Washington — World War I"], "Jefferson was the Declaration’s principal author. Madison connects with the Constitution and Washington with the Continental Army.")
    ]),
    trail("eight", "Complete the eight", "The other four Virginia-born presidents were William Henry Harrison (9th), John Tyler (10th), Zachary Taylor (12th), and Woodrow Wilson (28th). Harrison died shortly after taking office; Tyler succeeded him. Taylor was a military general before his presidency. Wilson served during World War I. Birthplace does not tell a person’s entire story or explain every achievement and harmful action.", [
      q("Which set completes the eight after Washington, Jefferson, Madison, and Monroe?", "Harrison, Tyler, Taylor, Wilson", ["Adams, Lincoln, Grant, Roosevelt", "Smith, Rolfe, Mason, Henry", "Lee, Jackson, Scott, Grant"], "William Henry Harrison, John Tyler, Zachary Taylor, and Woodrow Wilson complete the group of eight Virginia-born presidents."),
      q("Which Virginia-born president succeeded William Henry Harrison after his death?", "John Tyler", ["James Madison", "George Washington", "Thomas Jefferson"], "Tyler became president in 1841. He was the first vice president to succeed to the presidency after a president’s death."),
      q("Why distinguish birthplace from a president’s later home?", "The nickname counts birthplace, while a life can connect many states", ["Every president stayed in one town", "Presidents never traveled", "Birthplace proves every policy was good"], "Taylor was born in Virginia but grew up in Kentucky. Evaluating a president also requires studying actions and their effects.")
    ])
  ],
  "VS.13": [
    trail("industries", "Match places with work", "Virginia’s economy includes agriculture, seafood, manufacturing, technology, government, military work, and services. Harbors support Norfolk’s shipping and nearby shipbuilding; farms produce poultry, cattle, dairy, apples, and peanuts. Coal and timber are natural resources. Historic sites, parks, and beaches support tourism. A good is an object; a service is work performed for someone.", [
      q("Which geographic feature especially supports Norfolk’s shipping industry?", "A deep harbor connected to ocean routes", ["The highest mountain peak", "A desert", "A landlocked lake"], "Navigable water connects ships with ocean routes. Geography helps explain Hampton Roads’ economy."),
      q("Which field-trip purchase is a service?", "A guided museum tour", ["A bag of peanuts", "An apple", "A wooden chair"], "A tour is work performed for visitors. Museums, parks, hotels, and restaurants help support tourism jobs."),
      q("Which set contains agricultural products grown or raised in Virginia?", "Poultry, apples, and peanuts", ["Ocean liners and software", "Constitutions and ballots", "Coal and ironclad ships"], "Agriculture includes crops and animals. Manufacturing, natural-resource extraction, and services are other parts of the economy.")
    ]),
    trail("innovation", "Send an idea around the world", "Exports are goods or services sold abroad; imports come from abroad. Transportation, communication, and research help exchange products and ideas. Virginia’s technology businesses and internet infrastructure connect customers worldwide. Innovation changes opportunities and skills needed for jobs. People moving to Virginia contribute knowledge and traditions that shape its economy.", [
      q("A Virginia company buys equipment from another country. What is that equipment to Virginia?", "An import", ["An export", "A poll tax", "A charter"], "Imports come in; exports go out. Equipment sold from Virginia to another country would be an export."),
      q("How can Virginia software help customers in another country?", "Digital communication carries ideas and services across borders", ["Only physical objects can be traded", "Technology stops every new job", "Every customer must move to Virginia"], "Technology connects Virginia with global markets. Software and other services can reach distant customers."),
      q("A new tool changes a business. What is a thoughtful question to ask?", "How does it affect workers’ skills, jobs, and customers?", ["Does every invention help everyone equally?", "Can we ignore the people using it?", "Does history stop changing?"], "Innovation can improve work and create jobs while changing needed skills. Evidence helps explain benefits and challenges.")
    ])
  ]
};

export function solGuideUrl(missionId: MissionId) {
  return "https://www.solpass.org/z-site/va/2023Standards/vs" + missionId.split(".")[1] + "-2023.php";
}

export const SOL_FACT_CHECK_SOURCES: Partial<Record<MissionId, readonly { label: string; url: string }[]>> = {
  "VS.7": [
    { label: "NPS: Hampton Roads ironclads", url: "https://www.nps.gov/civilwar/search-battles-detail.htm?battleCode=va008" },
    { label: "NPS: Mary Jane Richards and the evidence", url: "https://www.nps.gov/rich/learn/historyculture/mary-jane-richards.htm" }
  ],
  "VS.8": [
    { label: "U.S. House history: Langston and contested elections", url: "https://history.house.gov/Exhibitions-and-Publications/BAIC/Historical-Essays/Fifteenth-Amendment/Temporary-Farewell/" }
  ]
};
