import type { MissionId } from '../domain/mission';

type Beat = readonly [label: string, explanation: string];
export interface StoryAnimationLesson { title: string; steps: readonly [Beat, Beat, Beat]; }
const lesson = (title: string, ...steps: [Beat, Beat, Beat]): StoryAnimationLesson => ({ title, steps });

/** Original visual scripts for the three stops in MISSION_STORIES.
 * Sources are the linked source on each story. Illustrations are conceptual;
 * routes, numbers of symbols, positions, and elapsed animation time are not historical measurements.
 */
export const STORY_ANIMATIONS: Record<MissionId, readonly [StoryAnimationLesson, StoryAnimationLesson, StoryAnimationLesson]> = {
  'VS.1': [
    lesson('Watch water find its way downhill', ['Rain reaches land', 'Rain and melting snow supply water high in the landscape. Follow the blue drops.'], ['Streams join', 'Gravity pulls water downhill. Small streams meet and add their water to a larger river.'], ['A river continues', 'The river follows lower ground. The land’s shape guides its route; water does not always flow east.']),
    lesson('Why a waterfall can help a town grow', ['A boat approaches', 'A loaded boat can travel through the deeper, calmer water below the Fall Line.'], ['Rocks interrupt travel', 'Rapids and waterfalls block the boat’s path upstream. Watch it stop before the rocks.'], ['Move the cargo', 'People unload the cargo and carry it around the obstacle. Warehouses and roads can grow near this meeting point.']),
    lesson('Connect an inland river to the ocean', ['Load near a town', 'Boats can carry heavy goods along a navigable stretch of river.'], ['Reach the bay', 'Many Virginia rivers connect inland communities to the Chesapeake Bay.'], ['Connect to the Atlantic', 'The bay opens to the Atlantic Ocean. This connects river travel with journeys to distant places.']),
  ],
  'VS.2': [
    lesson('Living communities tell their own stories', ['A living community', 'Virginia’s tribal nations are communities today, with distinct histories and identities.'], ['Listen to its voices', 'A community’s educators and museums share knowledge about its past and present.'], ['Ask whose story', 'Learn which community a source represents. One voice cannot speak for every tribal nation.']),
    lesson('An object keeps its connections', ['Notice the object', 'A pottery fragment is a clue, but it is not the whole story.'], ['Look around it', 'Soil layers and nearby objects connect the fragment to a place and other evidence.'], ['Keep clues together', 'Leave the fragment in place and tell a responsible adult. Recording its context helps archaeologists investigate.']),
    lesson('Build an explanation from several sources', ['Listen', 'A spoken account can preserve experiences and community knowledge.'], ['Compare', 'Compare the account with objects, places, and written records. Ask who created each source.'], ['Keep asking', 'When sources differ, investigate their context and purpose. A fuller explanation connects several kinds of evidence.']),
  ],
  'VS.3': [
    lesson('Jamestown: access does not mean safety', ['Follow the water route', 'In 1607, English colonists arrived by ship in the homeland of the Powhatan peoples.'], ['Reach deep water', 'Deep water near the James River shore helped ships approach the settlement.'], ['Weigh two needs', 'Ship access helped transport, but unhealthy drinking water and disease endangered people. A good harbor was not enough.']),
    lesson('Survival needs more than a river', ['Supplies are needed', 'Food and other supplies had to reach people at Jamestown. A route alone could not feed them.'], ['Connections break down', 'Supplies did not always arrive when needed. Food shortages, disease, and conflict worsened the crisis.'], ['A difficult winter', 'During the Starving Time of 1609–1610, many colonists died. Several causes combined; no single symbol explains every loss.']),
    lesson('Representation: who has a voice?', ['People have concerns', 'Government makes decisions that affect people in a community.'], ['Representatives meet', 'Representatives met in Virginia’s first legislative assembly in 1619.'], ['Notice the boundary', 'Many people had no voice there. Women, Indigenous peoples, and enslaved people were excluded from representation.']),
  ],
  'VS.4': [
    lesson('Tobacco takes work at every stage', ['Plant and tend', 'Workers plant and tend tobacco. A cash crop is grown mainly to sell.'], ['Harvest the leaves', 'Workers gather the leaves after the plants grow. Every stage requires labor.'], ['Dry for sale', 'Leaves are dried before sale. Enslaved people were increasingly forced to do this work without freedom.']),
    lesson('Follow a hogshead to the river', ['Pack the crop', 'Dried tobacco is packed in a large barrel called a hogshead.'], ['Move to the landing', 'Workers move the heavy barrel to a river landing. River access connects fields to trade.'], ['Load the ship', 'A ship carries the cargo onward. Farmers, barrel makers, carriers, and sailors are connected by the shipment.']),
    lesson('Follow the goods—and ask about power', ['Tobacco travels', 'Tobacco moves from Virginia to overseas buyers through Atlantic trade.'], ['Payment returns', 'Buyers pay for the crop. Plantation owners could profit from those sales.'], ['Profit is unequal', 'Enslaved workers were denied freedom and control over their labor. The money did not represent equal benefits for everyone.']),
  ],
  'VS.5': [
    lesson('A declaration begins a new claim', ['Announce independence', 'In 1776, the Declaration announced separation from Great Britain.'], ['The war continues', 'The announcement did not make Britain agree. Fighting and difficult choices continued.'], ['Test the promise', 'The document expressed liberty and equality, while enslaved people remained unfree and many people lacked equal rights.']),
    lesson('Yorktown: land and sea work together', ['Close the land routes', 'American and French armies surround British forces at Yorktown on land.'], ['Block the sea route', 'A French fleet blocks the route through the lower Chesapeake Bay. The ships are shown at sea, not circling the town.'], ['Work together', 'The land siege and naval blockade work together. Cornwallis’s army surrenders in 1781; the peace treaty comes later.']),
    lesson('A victory and a treaty do different jobs', ['A military turning point', 'The 1781 surrender at Yorktown is a major turning point in the war.'], ['Negotiate peace', 'Governments still need to negotiate a peace agreement. The timeline leaves a gap for this work.'], ['Recognize independence', 'The Treaty of Paris in 1783 formally recognizes U.S. independence. People still experience freedom and security unequally.']),
  ],
  'VS.6': [
    lesson('One government, three different jobs', ['Make laws', 'Congress is the legislative branch. Its job includes making laws.'], ['Carry out laws', 'The president leads the executive branch, which carries out laws.'], ['Interpret laws', 'Federal courts are the judicial branch. The branches have different powers and ways to limit one another.']),
    lesson('Turn a written framework into action', ['Start with a plan', 'The Constitution sets out the structure and powers of the national government.'], ['Put people in office', 'Washington becomes the first president in 1789. People and institutions must put the plan into action.'], ['Set an example', 'Early decisions establish precedents for later leaders. The government still excludes many people from political participation.']),
    lesson('The Bill of Rights adds protections', ['Amend the framework', 'An amendment is an official change or addition to the Constitution.'], ['Add ten amendments', 'The first ten amendments become the Bill of Rights in 1791. These ten tiles represent those amendments.'], ['Use and protect rights', 'Protections include speech and religion. Their meaning in daily life also depends on interpretation and enforcement.']),
  ],
  'VS.7': [
    lesson('Put the retreat in the story of the war', ['Understand secession', 'Southern states seceded to protect slavery. This cause belongs in the explanation of the Civil War.'], ['Four years of war', 'By April 1865, Lee’s Confederate army is retreating through Virginia. The line shows sequence, not an exact route.'], ['Sailor’s Creek', 'On April 6, Lee’s army suffers major losses at Sailor’s Creek. The retreat continues toward river crossings.']),
    lesson('Why the wagon bridge mattered', ['A river slows movement', 'People, animals, and supplies need a way across the Appomattox River near Farmville.'], ['Keep a crossing open', 'On April 7, Union troops preserve the lower wagon bridge after Confederate troops try to destroy the crossings.'], ['Pursuit continues', 'Union troops can continue across the wagon bridge. The high railroad bridge and lower wagon bridge are different crossings.']),
    lesson('An army surrenders; the law changes later', ['April 9, 1865', 'Lee surrenders his Army of Northern Virginia to Grant at Appomattox.'], ['Other armies remain', 'This ends the fighting of Lee’s army. Other Confederate armies surrender later.'], ['December 1865', 'The Thirteenth Amendment abolishes slavery except as punishment for a crime. Military surrender and legal change are different events.']),
  ],
  'VS.8': [
    lesson('Freedom opens possibilities for daily life', ['Change the law', 'The Thirteenth Amendment abolishes slavery in 1865, except as punishment for a crime.'], ['Make everyday choices', 'Freed people seek family reunions, paid work, and control over their lives.'], ['Build communities', 'Schools and independent community organizations help people shape their futures.']),
    lesson('Equal protection: a promise to examine', ['Define citizenship', 'The Fourteenth Amendment establishes citizenship for people born or naturalized in the United States and subject to its jurisdiction.'], ['Require equal protection', 'It requires states to provide equal protection of the laws.'], ['Check daily experience', 'Compare the written guarantee with evidence from schools, courts, and community life. A law does not prove fair treatment everywhere.']),
    lesson('Voting rights need protection in practice', ['Protect the vote', 'The Fifteenth Amendment bars denying voting rights because of race, color, or previous enslavement.'], ['Barriers remain', 'Threats and discriminatory barriers prevent many Black citizens from voting despite the amendment.'], ['Work for enforcement', 'People organize and challenge unfair treatment. The amendment does not mean that everyone can vote safely.']),
  ],
  'VS.9': [
    lesson('A resource needs people and a route', ['Find materials', 'Forests supply timber; coalfields supply coal. These are resources for industry.'], ['Do the work', 'Workers use tools and skills to gather materials. Mining and logging can bring hazards and environmental costs.'], ['Prepare to move', 'Heavy materials need connections to the places that will use or sell them.']),
    lesson('A bridge makes a railway connection', ['Load the train', 'A train can carry heavy cargo from a source toward a market.'], ['Cross the river', 'A railway bridge joins the tracks across a river. Watch the train remain on the rails.'], ['Complete the route', 'Connected tracks let the cargo reach its destination. High Bridge is a real Virginia example; this route is a model.']),
    lesson('Delivery connects a town’s economy', ['Goods arrive', 'The railway delivers materials to factories and markets.'], ['People make and sell', 'Workers transform or sell goods. Connected businesses can help a town grow.'], ['Look at people’s lives', 'Growth can bring jobs and difficult working conditions. Workers’ and residents’ accounts add evidence beyond profits.']),
  ],
  'VS.10': [
    lesson('The home front supports people in service', ['Make supplies', 'Civilian workers produce food, clothing, and equipment at farms, factories, and shipyards.'], ['Conserve materials', 'Families avoid waste. During World War II, rationing limits purchases of some scarce goods.'], ['Pack what is needed', 'Supplies are prepared for delivery. Work at home connects to military service far away.']),
    lesson('Every link matters in a supply chain', ['Pack the goods', 'Workers pack supplies so they can travel.'], ['Connect land and sea', 'Roads and railways bring cargo to ports, where workers load ships.'], ['Continue the journey', 'Ships carry supplies onward. A delay at one link can hold up the whole delivery.']),
    lesson('Supplies and letters connect different lives', ['Supplies reach service members', 'Service members depend on goods made and moved by many other people.'], ['News travels home', 'Letters connect people who are separated. Families face waiting, worries, and sometimes loss.'], ['Compare experiences', 'A service member’s letter and a worker’s account show different parts of wartime life. Neither speaks for everyone.']),
  ],
  'VS.11': [
    lesson('Students turn a concern into collective action', ['Unequal conditions', 'Black students at Moton High School face crowded, unequal conditions under segregation.'], ['Students organize', 'Barbara Johns helps organize the student strike in Farmville in 1951.'], ['A legal challenge grows', 'Students, families, and lawyers pursue a case that becomes part of Brown v. Board of Education.']),
    lesson('A local case joins a national decision', ['A Virginia case', 'The Moton students’ lawsuit joins the cases considered in Brown v. Board of Education.'], ['The Court decides', 'In 1954, the Supreme Court rules racial segregation in public schools unconstitutional.'], ['Follow what happens next', 'A court ruling changes the law, but access to school still depends on what people and governments do next.']),
    lesson('Follow the years when schools were closed', ['1959: schools close', 'Prince Edward County closes its public schools rather than integrate them.'], ['Years without equal access', 'The schools remain closed through the following years. Black children are especially harmed; many lose years of schooling.'], ['1964: schools reopen', 'Public schools reopen in 1964 after continued struggle. The 1954 decision had not brought immediate equal access.']),
  ],
  'VS.12': [
    lesson('Eight birthplaces make a Virginia connection', ['Locate a birthplace', 'A birthplace is one fact about a person’s life.'], ['Count eight presidents', 'Eight U.S. presidents were born in Virginia. Each tile represents one of those eight people.'], ['Ask what comes next', 'Birthplace does not tell us every place a person lived or what their decisions did. Investigate the whole life.']),
    lesson('A complete sequence includes John Adams', ['Washington: 1789', 'George Washington begins as the first U.S. president in 1789.'], ['Adams: 1797', 'John Adams, born in Massachusetts, serves between Washington and Jefferson. A Virginia-only list leaves him out.'], ['Jefferson, then Madison', 'Jefferson begins in 1801 and Madison in 1809. This is a sequence of presidencies, not a map of birthplaces.']),
    lesson('A legacy needs more than a portrait', ['Read a decision', 'Laws, speeches, and letters show what a leader said or did.'], ['Listen to affected people', 'Accounts from people affected by those decisions can show benefits, harms, and contradictions.'], ['Build a fuller account', 'Washington, Jefferson, and Madison helped shape the nation and also enslaved people. Both belong in an evidence-based account.']),
  ],
  'VS.13': [
    lesson('A product starts with connected work', ['Grow a product', 'This example starts on a Virginia farm. Land, weather, equipment, and people all matter.'], ['Prepare an order', 'A buyer in another country wants the product. Workers prepare it for travel.'], ['Begin an export journey', 'Selling a product to another country is an export. Services and technology are also parts of Virginia’s economy.']),
    lesson('Watch cargo transfer from land to sea', ['Travel inland', 'A truck or train carries goods toward a port.'], ['Transfer the cargo', 'Port workers and equipment move cargo from land transport onto a ship.'], ['Sail onward', 'The ship connects the land route with ocean trade. This is a possible journey, not a tracked shipment.']),
    lesson('One shipment, two points of view', ['Leaving the seller', 'For Virginia in the United States, a product sold to another country is an export.'], ['Reaching the buyer', 'For the country buying it, that same shipment is an import.'], ['Check the numbers', 'Before comparing trade charts, check dates, sources, and what each number counts. The picture shows no measured trade totals.']),
  ],
};
